### ISSUE TITLE
Testing activities/workflows in isolation

### ISSUE THREAD

**Issue by smndtrl** [h7kanna/temporal-rust-worker#4]
Great work creating a easy to use rust API.

Could you create an example of how to test the activities/workflows without running a temporal instance?

**Comment by h7kanna** [comment]
Hi, 
The official/upstream Rust SDK is not production-ready(prototype only) and lacks most of the features from the other SDKs(Java/Go).
It also lacks the testing suite.

**Comment by smndtrl** [comment]
Oh :( Sad to here about the current state.

I'll just continue for now and keep make activities to being one function each. It works great so far. 

Thanks again for this fork. Finally a way to work in Rust with background workflows
